version: "3.3"

services:
  web:
    container_name: service-agendamento
    build:
      context: .
    volumes:
      - ".:/app"
      - "/node_modules"
    ports:
      - 3000:3000
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASS: ${MARIADB_PASS}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PORT: ${MARIADB_PORT}
    depends_on:
      - maria-db-agendamento

  maria-db-agendamento:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASS}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASS}
    ports:
      - 3306:3306
    
volumes:
  mariadb-data:


